<a href="https://colab.research.google.com/github/DiegoRomanCortes/AED/blob/master/Auxiliar_1_prim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pregunta 2
En esta pregunta resolveremos varios ejercicios cortos y con dificultad relativamente sencilla
que nos muestran cómo trabajar con los arreglos de NumPy.
1. Crear un arreglo de enteros de tamaño 11, que sólo contenga ceros. Modificar el primer y el
último ítem del arreglo para que contengan ambos un 5.
2. Crear una matriz de 3x3 que contenga los números del 5 al 13 e imprimirla.
3. Crear una matriz de 5x5 con ceros. Convertir todos los ceros en 2s e imprimir la matriz.
4. Crear un arreglo que contenga los números enteros del 32 al 67. Imprimir el arreglo y sus
dimensiones. Luego invertirlo utilizando una matriz con unos enteros como matriz auxiliar
y volver a imprimirlo. Imprimir también sus dimensiones. Finalmente, convertir el arreglo en
una matriz de 6x6 e imprimirla. Imprimir las dimensiones de la matriz.
5. Crear un arreglo de Strings de tamaño 5 que soporte cadenas de letras de tamaño máximo 20. Rellenar el primer y el último elemento con cualquier palabra de máximo ese tamaño e
imprimir el arreglo.
6. Crear un arreglo de 15 decimales y llenarlos de tal forma que el primer elemento contenga
un 3.30 y cada elemento siguiente sea mayor que el anterior en 0.3.

In [0]:
import numpy as np

In [2]:
a = np.zeros(11)
a[0] = 5
a[-1] = 5
print(a)

[5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]


In [6]:
b = np.arange(5,14).reshape(3,3)
print(b)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [7]:
c = np.zeros((3,3))
c[c==0]=2
print(c)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [34]:
d = np.arange(32,68)
print(d, d.shape)

aux = np.zeros((len(d),len(d)), dtype = int)
i = 0
j = 0

while i < len(aux):
  while j < len(aux[0]):
    if i + j == len(aux) - 1:
      aux[i][j] = 1
    j += 1
  j = 0  
  i += 1

d = d @ aux
print(d, d.shape)

d = d.reshape(6,6)
print(d)

[32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55
 56 57 58 59 60 61 62 63 64 65 66 67] (36,)
[67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44
 43 42 41 40 39 38 37 36 35 34 33 32] (36,)
[[67 66 65 64 63 62]
 [61 60 59 58 57 56]
 [55 54 53 52 51 50]
 [49 48 47 46 45 44]
 [43 42 41 40 39 38]
 [37 36 35 34 33 32]]


In [39]:
array_e = np.empty(5, dtype='U20')
array_e[0] = "Hola amig@"
array_e[4] = "Adiós amig@"
print(array_e, "\n")

['Hola amig@' '' '' '' 'Adiós amig@'] 



#Pregunta 3
En esta pregunta recordaremos lo que es la recursión, contenido que se vio en el curso de Introducción a la Programación. Imprimiremos todos los cursos que son requisitos para poder tomar
Mecánica, curso que es de tercer semestre.

Primero, modelaremos la clase Curso. Un curso debe tener un String con su nombre, un String
con su código de curso, un entero con su cantidad de UDs, un entero con el semestre al que
corresponde y un arreglo que contenga los cursos que son requisitos para poder cursarlo. El único método que dicha clase debe tener es uno que imprima toda la información del curso en pantalla.
Luego crearemos instancias de los cursos con los ramos que son necesarios para cursar FI2001
Mecánica. 

Los requisitos de Mecánica son:
* FI1002 Sistemas Newtonianos
* MA1002 Cálculo Diferencial e Integral
* MA1102 Álgebra Lineal

Para poder cursar Sistemas Newtonianos se requiere haber cursado:
* CC1001 Herramientas Computacionales
* FI1001 Introducción a la Física.

Para poder cursar Álgebra Lineal y Cálculo Diferencial e Integral es necesario haber cursado:
* MA1001 Introducción al Cálculo y
* MA1101 Introducción al Álgebra.

Una vez creadas todas las instancias, imprimiremos los cursos que son requisitos para haber
cursado Mecánica de forma recursiva, utilizando el método que creamos para ello. Asumiremos que
los requisitos simultáneos son requisitos estrictos y no nos importará imprimir más de una vez un
curso.

In [77]:
class Curso:
  def __init__(self, nombre, codigo, SCTs, semestre, requisitos):
    self.nombre = nombre
    self.codigo = codigo
    self.SCTs = SCTs
    self.semestre = semestre
    self.requisitos = requisitos

  def mostrarInfo(self):
    print("Nombre: ", self.nombre)
    print("Código: ", self.codigo)
    print("Créditos: ", self.SCTs)
    print("Semestre: ", self.semestre, "\n")

  def mostrarRequisitos(self, req = []):
    if self.requisitos == None:
      return None
    else:
      for curso in self.requisitos:
        if curso not in req:
          req.append(curso)
          curso.mostrarInfo()
        curso.mostrarRequisitos(req)

calc = Curso("Introducción al Cálculo", "MA1001", 6, 1, None)
alg = Curso("Introducción al Álgebra", "MA1101", 6, 1, None)
herr = Curso("Herramientas Computacionales", "CC1000", 6, 1, None)
fis = Curso("Introducción a la Física Newtoniana", "FI1001", 6, 1, None)
ingI = Curso("Introducción a la Ingeniería I", "EI1101", 6, 1, None)
quim = Curso("Química", "CM1001", 6, 1, None)

lineal = Curso("Álgebra Lineal", "MA1102", 6, 2, [calc, alg])
diff = Curso("Cálculo Diferencial e Integral","MA1002",  6, 2, [calc, alg])
sist = Curso("Sistemas Newtonianos", "FI1002", 6, 2, [herr, fis])
progr = Curso("Introducción a la Programación", "CC1002", 6, 2, None)
ingII = Curso("Introducción a la Ingienería II","EI1102", 6, 2, [ingI])

meca = Curso("Mecánica", "FI2001", 6, 3, [sist, diff, lineal])
cvv = Curso("Cálculo en Varias Variables", "MA2001",6, 3, [lineal, diff])
edo = Curso("Ecuaciones Diferenciales Ordinarias", "MA2601", 6, 3, [diff, lineal])
taller = Curso("Taller de Proyecto", "EI2001", 3, 3, [cvv])

caa = Curso("Cálculo Avanzado y Aplicaciones", "MA2002", 6,4,[cvv, edo])
electro = Curso("Electromagnetismo", "FI2002", 6, 4, [meca, edo, cvv])
metexp = Curso("Métodos Experimentales", "FI2003", 6, 4, [ingII, quim, meca, cvv, edo])
termo = Curso("Termodinámica", "FI2004", 6, 4, [quim, cvv, meca])

vibra = Curso("Vibraciones y Ondas", "FI3001", 6, 5, [meca, caa])
mmf = Curso("Métodos Matemáticos para la Física", "FI3002", 6, 5, [cvv, electro])
fisexpI = Curso("Física Experimental I", "FI3003", 6, 5, [electro, metexp])
probayesta = Curso("Probabilidades y Estadística", "MA3403", 6, 5, [cvv])

meclas = Curso("Mecánica Clásica", "FI3101", 6, 6, [vibra])
fismod = Curso("Física Moderna", "FI3102", 6, 6, [vibra, electro])
metnum = Curso("Métodos Numéricos para la Ciencia e Ingenieria", "FI3104", 6, 6, [caa, termo])
fisexpII = Curso("Física Experimental II","FI4003", 6, 6, [fisexpI])

elecdin = Curso("Electrodinámica", "FI4004", 9, 7, [electro, mmf])
mecuant = Curso("Mecánica Cuántica", "FI4001", 9, 7, [fismod, mmf])

mecest = Curso("Mecánica Estadística", "FI4104", 9, 8, [meclas, probayesta, fismod, termo])
introfissol = Curso("Introduciión a la Física del Sólido", "FI4101", 6, 8, [mecuant, termo])

introfissol.mostrarRequisitos()

Nombre:  Mecánica Cuántica
Código:  FI4001
Créditos:  9
Semestre:  7 

Nombre:  Física Moderna
Código:  FI3102
Créditos:  6
Semestre:  6 

Nombre:  Vibraciones y Ondas
Código:  FI3001
Créditos:  6
Semestre:  5 

Nombre:  Mecánica
Código:  FI2001
Créditos:  6
Semestre:  3 

Nombre:  Sistemas Newtonianos
Código:  FI1002
Créditos:  6
Semestre:  2 

Nombre:  Herramientas Computacionales
Código:  CC1000
Créditos:  6
Semestre:  1 

Nombre:  Introducción a la Física Newtoniana
Código:  FI1001
Créditos:  6
Semestre:  1 

Nombre:  Cálculo Diferencial e Integral
Código:  MA1002
Créditos:  6
Semestre:  2 

Nombre:  Introducción al Cálculo
Código:  MA1001
Créditos:  6
Semestre:  1 

Nombre:  Introducción al Álgebra
Código:  MA1101
Créditos:  6
Semestre:  1 

Nombre:  Álgebra Lineal
Código:  MA1102
Créditos:  6
Semestre:  2 

Nombre:  Cálculo Avanzado y Aplicaciones
Código:  MA2002
Créditos:  6
Semestre:  4 

Nombre:  Cálculo en Varias Variables
Código:  MA2001
Créditos:  6
Semestre:  3 

Nombre:  